python_tests(
    name="module_a",
    sources=["test_module_a.py"],
    dependencies=["src:module_a"],
)

python_tests(
    name="module_b",
    sources=["test_module_b.py"],
    dependencies=["src:module_b"],
)

python_tests(
    name="module_c",
    sources=["test_module_c.py"],
    dependencies=["src:module_c"],
)