[GLOBAL]
pants_version = "2.14.0"

backend_packages = [
  "pants.backend.python",
  "pants.backend.python.lint.black",
  "pants.backend.python.lint.pylint",
  "pants.backend.python.lint.isort",
  "pants.backend.python.typecheck.mypy",
]

[python]
interpreter_constraints = ["CPython>=3.8.*,<3.9"]
enable_resolves = true

[python.resolves]
my_module = "build-support/my_module.txt"

[python-repos]
indexes.add = ["%(env.PIP_EXTRA_INDEX_URL)s"]

[black]
interpreter_constraints = ["CPython>=3.8.*,<3.9"]
lockfile = "build-support/black.lockfile"
version = "black==22.3.0"

[mypy]
interpreter_constraints = ["CPython>=3.8.*,<3.9"]
extra_type_stubs = ["types-PyYAML", "pandas-stubs"]
lockfile = "build-support/mypy.lockfile"

[source]
root_patterns = ["src", "test"]

[pylint]
extra_requirements = ["pytest"]
config = ".pylintrc"
lockfile = "build-support/pylint.lockfile"

[test]
output = "all"
use_coverage = true
report_dir = "dist/coverage/pytest_results"

[pytest]
args="-vv"

[coverage-py]
report = ["console", "xml"]
global_report = true
output_dir = "dist/coverage/python"
config = ".coveragerc"

[anonymous-telemetry]
enabled = false
